package com.majiang.community.model;

import lombok.Data;

@Data
public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.ID
     *
     * @mbg.generated Fri Aug 09 10:04:53 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.TITLE
     *
     * @mbg.generated Fri Aug 09 10:04:53 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.DESCRIPTION
     *
     * @mbg.generated Fri Aug 09 10:04:53 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.GMTCREATE
     *
     * @mbg.generated Fri Aug 09 10:04:53 CST 2019
     */
    private Long gmtcreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.GMTMODIFIED
     *
     * @mbg.generated Fri Aug 09 10:04:53 CST 2019
     */
    private Long gmtmodified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.CREATOR
     *
     * @mbg.generated Fri Aug 09 10:04:53 CST 2019
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.TAGS
     *
     * @mbg.generated Fri Aug 09 10:04:53 CST 2019
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.VIEWCOUNT
     *
     * @mbg.generated Fri Aug 09 10:04:53 CST 2019
     */
    private Integer viewcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.COMMENTCOUNT
     *
     * @mbg.generated Fri Aug 09 10:04:53 CST 2019
     */
    private Integer commentcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.LIKECOUNT
     *
     * @mbg.generated Fri Aug 09 10:04:53 CST 2019
     */
    private Integer likecount;

}